import type { Config } from "tailwindcss";

// Design tokens transcribed from aurelian_minimalist.md — the single
// source of truth for this design system. Keep in sync with that file.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9fc",
        "surface-dim": "#dbd9dd",
        "surface-bright": "#fbf9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f6",
        "surface-container": "#efedf0",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e3e2e5",
        "on-surface": "#1b1b1e",
        "on-surface-variant": "#444748",
        "inverse-surface": "#303033",
        "inverse-on-surface": "#f2f0f3",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        secondary: "#775a19",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed488",
        "on-secondary-container": "#785a1a",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1d",
        "on-tertiary-container": "#838486",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary-fixed": "#e2e2e4",
        "tertiary-fixed-dim": "#c6c6c8",
        "on-tertiary-fixed": "#1a1c1d",
        "on-tertiary-fixed-variant": "#454749",
        background: "#fbf9fc",
        "on-background": "#1b1b1e",
        "surface-variant": "#e3e2e5",
        // Accent aliases used directly in copy for clarity (same values
        // as documented in the "Colors" section of the design system).
        "accent-gold": "#c5a059",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "serif"],
        "headline-lg": ["var(--font-playfair)", "serif"],
        "headline-lg-mobile": ["var(--font-playfair)", "serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        display: [
          "80px",
          { lineHeight: "88px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-unit": "8px",
        gutter: "32px",
        "margin-desktop": "80px",
        "margin-mobile": "24px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
